"""initial schema

Revision ID: 204614c8c511
Revises: 
Create Date: 2026-09-26 16:22:49.390423

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '204614c8c511'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('rera_orn', sa.String(length=40), nullable=True),
    sa.Column('trade_license', sa.String(length=60), nullable=True),
    sa.Column('emirate', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_agencies_updated_at'), 'agencies', ['updated_at'], unique=False)
    op.create_table('api_keys',
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_agency_id'), 'api_keys', ['agency_id'], unique=False)
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_updated_at'), 'api_keys', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('rera_brn', sa.String(length=40), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('areas', sa.JSON(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'email', name='uq_user_agency_email')
    )
    op.create_index(op.f('ix_users_agency_id'), 'users', ['agency_id'], unique=False)
    op.create_index(op.f('ix_users_external_ref'), 'users', ['external_ref'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_table('webhooks',
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_agency_id'), 'webhooks', ['agency_id'], unique=False)
    op.create_index(op.f('ix_webhooks_updated_at'), 'webhooks', ['updated_at'], unique=False)
    op.create_table('leads',
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('nationality', sa.String(length=60), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('campaign', sa.String(length=120), nullable=True),
    sa.Column('listing_reference', sa.String(length=80), nullable=True),
    sa.Column('purpose', sa.String(length=8), nullable=True),
    sa.Column('property_type', sa.String(length=32), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('areas', sa.JSON(), nullable=False),
    sa.Column('budget_min_aed', sa.Float(), nullable=True),
    sa.Column('budget_max_aed', sa.Float(), nullable=True),
    sa.Column('timeline', sa.String(length=40), nullable=True),
    sa.Column('payment_method', sa.String(length=16), nullable=True),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('stage_changed_at', sa.DateTime(), nullable=False),
    sa.Column('lost_reason', sa.String(length=160), nullable=True),
    sa.Column('assigned_agent_id', sa.String(length=36), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_band', sa.String(length=8), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_scored_at', sa.DateTime(), nullable=True),
    sa.Column('ai_broker_ref', sa.String(length=64), nullable=True),
    sa.Column('consent_marketing', sa.Boolean(), nullable=False),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('custom', sa.JSON(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'source', 'external_id', name='uq_lead_source_external')
    )
    op.create_index(op.f('ix_leads_agency_id'), 'leads', ['agency_id'], unique=False)
    op.create_index('ix_leads_agency_phone', 'leads', ['agency_id', 'phone'], unique=False)
    op.create_index('ix_leads_agency_stage', 'leads', ['agency_id', 'stage'], unique=False)
    op.create_index('ix_leads_agency_updated', 'leads', ['agency_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_leads_assigned_agent_id'), 'leads', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_leads_deleted_at'), 'leads', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_leads_updated_at'), 'leads', ['updated_at'], unique=False)
    op.create_table('listings',
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('listing_type', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('property_type', sa.String(length=32), nullable=False),
    sa.Column('community', sa.String(length=120), nullable=False),
    sa.Column('sub_community', sa.String(length=120), nullable=True),
    sa.Column('building', sa.String(length=160), nullable=True),
    sa.Column('emirate', sa.String(length=40), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('size_sqft', sa.Float(), nullable=True),
    sa.Column('price_aed', sa.Float(), nullable=False),
    sa.Column('rent_frequency', sa.String(length=8), nullable=True),
    sa.Column('furnished', sa.String(length=16), nullable=True),
    sa.Column('completion_status', sa.String(length=16), nullable=False),
    sa.Column('handover_date', sa.String(length=10), nullable=True),
    sa.Column('developer', sa.String(length=120), nullable=True),
    sa.Column('permit_number', sa.String(length=40), nullable=True),
    sa.Column('dld_number', sa.String(length=40), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=True),
    sa.Column('owner_phone', sa.String(length=32), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('portals', sa.JSON(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'reference', name='uq_listing_reference')
    )
    op.create_index(op.f('ix_listings_agency_id'), 'listings', ['agency_id'], unique=False)
    op.create_index(op.f('ix_listings_agent_id'), 'listings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_listings_deleted_at'), 'listings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_listings_updated_at'), 'listings', ['updated_at'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('webhook_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_delivery_pending', 'webhook_deliveries', ['status', 'next_attempt_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_agency_id'), 'webhook_deliveries', ['agency_id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_updated_at'), 'webhook_deliveries', ['updated_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    op.create_table('activities',
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=8), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_agency_id'), 'activities', ['agency_id'], unique=False)
    op.create_index(op.f('ix_activities_lead_id'), 'activities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_activities_listing_id'), 'activities', ['listing_id'], unique=False)
    op.create_index(op.f('ix_activities_updated_at'), 'activities', ['updated_at'], unique=False)
    op.create_index('ix_activity_lead_created', 'activities', ['lead_id', 'created_at'], unique=False)
    op.create_table('deals',
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('deal_type', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('offer_aed', sa.Float(), nullable=True),
    sa.Column('agreed_aed', sa.Float(), nullable=True),
    sa.Column('commission_pct', sa.Float(), nullable=True),
    sa.Column('commission_aed', sa.Float(), nullable=True),
    sa.Column('mou_signed_at', sa.DateTime(), nullable=True),
    sa.Column('transfer_date', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_agency_id'), 'deals', ['agency_id'], unique=False)
    op.create_index(op.f('ix_deals_agent_id'), 'deals', ['agent_id'], unique=False)
    op.create_index(op.f('ix_deals_lead_id'), 'deals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_deals_listing_id'), 'deals', ['listing_id'], unique=False)
    op.create_index(op.f('ix_deals_updated_at'), 'deals', ['updated_at'], unique=False)
    op.create_table('followups',
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_agency_id'), 'followups', ['agency_id'], unique=False)
    op.create_index(op.f('ix_followups_agent_id'), 'followups', ['agent_id'], unique=False)
    op.create_index(op.f('ix_followups_due_at'), 'followups', ['due_at'], unique=False)
    op.create_index(op.f('ix_followups_external_id'), 'followups', ['external_id'], unique=False)
    op.create_index(op.f('ix_followups_lead_id'), 'followups', ['lead_id'], unique=False)
    op.create_index(op.f('ix_followups_updated_at'), 'followups', ['updated_at'], unique=False)
    op.create_table('viewings',
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('location_note', sa.String(length=240), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viewings_agency_id'), 'viewings', ['agency_id'], unique=False)
    op.create_index(op.f('ix_viewings_agent_id'), 'viewings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_viewings_external_id'), 'viewings', ['external_id'], unique=False)
    op.create_index(op.f('ix_viewings_lead_id'), 'viewings', ['lead_id'], unique=False)
    op.create_index(op.f('ix_viewings_listing_id'), 'viewings', ['listing_id'], unique=False)
    op.create_index(op.f('ix_viewings_scheduled_at'), 'viewings', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_viewings_updated_at'), 'viewings', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_viewings_updated_at'), table_name='viewings')
    op.drop_index(op.f('ix_viewings_scheduled_at'), table_name='viewings')
    op.drop_index(op.f('ix_viewings_listing_id'), table_name='viewings')
    op.drop_index(op.f('ix_viewings_lead_id'), table_name='viewings')
    op.drop_index(op.f('ix_viewings_external_id'), table_name='viewings')
    op.drop_index(op.f('ix_viewings_agent_id'), table_name='viewings')
    op.drop_index(op.f('ix_viewings_agency_id'), table_name='viewings')
    op.drop_table('viewings')
    op.drop_index(op.f('ix_followups_updated_at'), table_name='followups')
    op.drop_index(op.f('ix_followups_lead_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_external_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_due_at'), table_name='followups')
    op.drop_index(op.f('ix_followups_agent_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_agency_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_deals_updated_at'), table_name='deals')
    op.drop_index(op.f('ix_deals_listing_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_lead_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_agent_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_agency_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index('ix_activity_lead_created', table_name='activities')
    op.drop_index(op.f('ix_activities_updated_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_listing_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_lead_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_agency_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_updated_at'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_agency_id'), table_name='webhook_deliveries')
    op.drop_index('ix_delivery_pending', table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_listings_updated_at'), table_name='listings')
    op.drop_index(op.f('ix_listings_deleted_at'), table_name='listings')
    op.drop_index(op.f('ix_listings_agent_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_agency_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_leads_updated_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_deleted_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_agent_id'), table_name='leads')
    op.drop_index('ix_leads_agency_updated', table_name='leads')
    op.drop_index('ix_leads_agency_stage', table_name='leads')
    op.drop_index('ix_leads_agency_phone', table_name='leads')
    op.drop_index(op.f('ix_leads_agency_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_webhooks_updated_at'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_agency_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_external_ref'), table_name='users')
    op.drop_index(op.f('ix_users_agency_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_api_keys_updated_at'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_agency_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_agencies_updated_at'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
